Converting constructor for iterator class
CExA-project/kokkos pull request #11
Opened 2024-04-11 08:12 UTC by yasahi-hpc

This PR aims at adding a missing converting constructor in Kokkos::RandomAccessIterator.

It now allows to construct a non-const iterator from const iterator.

```C++
auto it  = KE::begin(view_from)
auto cit = KE::cbegin(view_from)
bool cit2it = std::is_constructible_v<decltype(cit), decltype(it)>; // True
bool it2cit = std::is_constructible_v<decltype(it), decltype(cit)>; // False
```

2024-04-11 08:51 UTC, tpadioleau requested changes
Seems good to me.

A question though, I am surprised you don't need to declare other classes as `friend` because you are accessing private member variables of an other type ?

2024-04-11 08:51 UTC, tpadioleau commented on algorithms/src/std_algorithms/impl/Kokkos_RandomAccessIterator.hpp
> +  KOKKOS_FUNCTION RandomAccessIterator(
Other constructors are marked `explicit` so maybe also add it here.

2024-04-11 09:09 UTC, tpadioleau commented on algorithms/src/std_algorithms/impl/Kokkos_RandomAccessIterator.hpp
> +  KOKKOS_FUNCTION RandomAccessIterator(
> Should I make it explicit?

I tend to prefer explicit conversion but that can be discussed with Kokkos dev team

2024-04-11 09:09 UTC, tpadioleau approved these changes

2024-04-11 09:14 UTC, yasahi-hpc commented on algorithms/src/std_algorithms/impl/Kokkos_RandomAccessIterator.hpp
> +  KOKKOS_FUNCTION RandomAccessIterator(
I may also prefer your way. Since Christian explicitly say that a converting_constructor is missing, I made it implicit this time. Maybe discussed in core.

2024-04-16 06:29 UTC, yasahi-hpc commented
Closes this PR, it is merged to develop [\#6929] (https://github.com/kokkos/kokkos/pull/6929).

2024-04-16 06:29 UTC, closed without merging